name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Run tests
        run: docker run my-app npm test

      - name: Push Docker image to Docker Hub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker tag my-app $DOCKER_USERNAME/my-app:latest
          docker push $DOCKER_USERNAME/my-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Render
        run: |
          curl -fsSL https://render.com/cli/install.sh | bash
          export PATH="$HOME/.render/bin:$PATH"
          render login
          render deploy --docker --name my-app --env production
